# Site settings
title: Vijay Tadimeti
description: A portfolio blog about me, my work and projects
# baseurl: "vijaytadimeti" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g.

# User settings
username: Vijay Tadimeti
user_description: Masters Student
user_title: Software Developer
email: tadimetv@oregonstate.edu
instagram_username: vijay.tadimeti
github_username:  vijayvardhan94
linkedin_username:  Vijay Tadimeti

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
